// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaiZUI4GoNX15qmac7gOxF4dFD5XRXYVI',
    appId: '1:793574077319:web:d2c7ac6cfa163f03f19922',
    messagingSenderId: '793574077319',
    projectId: 'scrapcycle-60418',
    authDomain: 'scrapcycle-60418.firebaseapp.com',
    storageBucket: 'scrapcycle-60418.appspot.com',
    measurementId: 'G-VRLDHX9G8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8OqRQVG6l8w-R7N3e-J86aXVIYhQqAc',
    appId: '1:793574077319:android:9e86560f290ff9aaf19922',
    messagingSenderId: '793574077319',
    projectId: 'scrapcycle-60418',
    storageBucket: 'scrapcycle-60418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIMeFVohGXkH6re_q5XzhYXfAi6Mf1cOE',
    appId: '1:793574077319:ios:318172af715b47b3f19922',
    messagingSenderId: '793574077319',
    projectId: 'scrapcycle-60418',
    storageBucket: 'scrapcycle-60418.appspot.com',
    androidClientId: '793574077319-0puf5itirjnjn0dbk6nltqn7nvf70mcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIMeFVohGXkH6re_q5XzhYXfAi6Mf1cOE',
    appId: '1:793574077319:ios:318172af715b47b3f19922',
    messagingSenderId: '793574077319',
    projectId: 'scrapcycle-60418',
    storageBucket: 'scrapcycle-60418.appspot.com',
    androidClientId: '793574077319-0puf5itirjnjn0dbk6nltqn7nvf70mcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricelist',
  );
}
